import { MetadataRoute } from "next";
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      { userAgent: "CCBot", disallow: "/" },
      { userAgent: "ChatGPT-User", disallow: "/" },
      { userAgent: "GPTBot", disallow: "/" },
      { userAgent: "Google-Extended", disallow: "/" },
      { userAgent: "anthropic-ai", disallow: "/" },
      { userAgent: "Omgilibot", disallow: "/" },
      { userAgent: "Omgili", disallow: "/" },
      { userAgent: "FacebookBot", disallow: "/" },
      { userAgent: "Meta-ExternalAgent", disallow: "/" },
      { userAgent: "Meta-ExternalFetcher", disallow: "/" },
      { userAgent: "Diffbot", disallow: "/" },
      { userAgent: "Bytespider", disallow: "/" },
      { userAgent: "ImagesiftBot", disallow: "/" },
      { userAgent: "cohere-ai", disallow: "/" },
      { userAgent: "PerplexityBot", disallow: "/" },
      { userAgent: "Perplexity-User", disallow: "/" },
      { userAgent: "Amazonbot", disallow: "/" },
      { userAgent: "ClaudeBot", disallow: "/" },
      { userAgent: "Applebot", disallow: "/" },
      { userAgent: "Applebot-Extended", disallow: "/" },
      { userAgent: "Youbot", disallow: "/" },
      { userAgent: "Claude-User", disallow: "/" },
      { userAgent: "Claude-SearchBot", disallow: "/" },
      { userAgent: "diffbot", disallow: "/" },
      { userAgent: "webzio-extended ", disallow: "/" },
      { userAgent: "TikTokSpider", disallow: "/" },
      { userAgent: "SemrushBot-OCOB", disallow: "/" },
      { userAgent: "Petalbot", disallow: "/" },
      { userAgent: "VelenPublicWebCrawler", disallow: "/" },
      { userAgent: "TurnitinBot", disallow: "/" },
      { userAgent: "Timpibot", disallow: "/" },
      { userAgent: "OAI-SearchBot", disallow: "/" },
      { userAgent: "ICC-Crawler", disallow: "/" },
      { userAgent: "AI2Bot", disallow: "/" },
      { userAgent: "AI2Bot-Dolma", disallow: "/" },
      { userAgent: "DataForSeoBot", disallow: "/" },
      { userAgent: "AwarioBot", disallow: "/" },
      { userAgent: "AwarioSmartBot", disallow: "/" },
      { userAgent: "AwarioRssBot", disallow: "/" },
      { userAgent: "Google-CloudVertexBot", disallow: "/" },
      { userAgent: "PanguBot", disallow: "/" },
      { userAgent: "Kangaroo Bot", disallow: "/" },
      { userAgent: "Sentibot", disallow: "/" },
      { userAgent: "peer39_crawler", disallow: "/" },
      { userAgent: "cohere-training-data-crawler", disallow: "/" },
      { userAgent: "DuckAssistBot", disallow: "/" },
      { userAgent: "Scrapy", disallow: "/" },
      { userAgent: "Cotoyogi", disallow: "/" },
      { userAgent: "aiHitBot", disallow: "/" },
      { userAgent: "Factset_spyderbot", disallow: "/" },
      { userAgent: "FirecrawlAgent", disallow: "/" },
    ],
    sitemap: "https://comics-src.vercel.app/sitemap.xml",
  };
}
